server:
  profiles:
    active: dev
  servlet:
    context-path: /jsfspring
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: yns
    password: yns
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
        order_inserts: true
        order_updates: true

#  h2:
#    console:
#      enabled: true
#      path: /h2

  # data base configuration (Oracle/MySql/H2)
  #spring.datasource.url=jdbc:h2:mem:testdb
  #spring.datasource.username=sa
  #spring.datasource.password=
  #spring.datasource.driver-class-name=org.h2.Driver

  messages:
    basename: Bundle

  flyway:
    out-of-order: true
    baseline-on-migrate: true

logging:
  level:
    root: info
    logging:
      level:
        com:
          example: debug
    org:
      springframework:
        web: debug
      hibernate:
        SQL: debug
  file:
    name: 'c:\\logs\\log.log'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'


